GOOD_PICTURE_INDEX_BOOST = 1.5

BOOST_SEARCH_RESULTS_ON_NUM_USES = False
# Post-sorting position is still more influential.
BOOST_SEARCH_RESULTS_WEIGHT_POS = 5.0
BOOST_SEARCH_RESULTS_WEIGHT_USES = 1.0

NUM_USES_INCREMENT_TIME_BARRIER_GENERAL = 15

NUM_USES_INCREMENT_TIME_BARRIER_SAME_IP = 24 *3600
